version: '2'

services:
  edgeswitchmqtt:
        environment:
            TZ: "Europe/Berlin"
        hostname: edgeswitchmqtt
        image: pharndt/edgeswitchmqtt
        volumes:
            - ./config:/var/lib/edgeswitch-to-mqtt-gw:rw
        restart: always
